version: '3.7'
services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - DATABASE_PORT_3306_TCP_ADDR=mysql
      - DATABASE_PORT_3306_TCP_PORT=3306
    links:
      - mysql
      - redis
    volumes:
      - .:/app
      - /app/tmp
    command: sh setup_app.sh
  mysql:
    image: mysql:5.7.13
    environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_DATABASE=notifications_system_development
    command: mysqld --skip-ssl
  redis:
    image: "redis:4.0-alpine"
    ports:
      - "6379:6379"
    volumes:
      - .:/redis
    command: redis-server
  sidekiq:
    build: .
    links:
      - redis
      - mysql
    volumes:
      - .:/app
    command: bundle exec sidekiq -c 5 -q notifications
volumes:
  redis:
  db:
